### ISSUE TITLE
bug affichage vignettes

### ISSUE THREAD

**Issue by npayot** [jperon/pmb#1]
Bonjour,

J'ai utilisé cette image docker avec docker-compose et tout fonctionne à merveille sauf les couvertures des livres qui ne sont visibles ni dans l'opac, ni dans l'interface admin.
J'ai laissé les paramètres par défaut de book_pics_url (utilisation d'Amazon) et book_pics_show (sur 1). php5-curl a également été ajouté à la configuration du Dockerfile.
Une idée de solution?

**Comment by jperon** [comment]
Bonjour,

Ne seriez-vous pas derrière un proxy ? J'ai eu la même difficulté au départ, mais après avoir configuré la bonne adresse de proxy dans `Administration > Outils > Paramètres > Paramètres généraux > curl_proxy` et dans `Administration > Outils > Paramètres > OPAC > curl_proxy`, cela fonctionne normalement.

**Comment by npayot** [comment]
Je suis en localhost donc en principe sans proxy, mais après récupération du dernier Dockerfile, le problème s'est résolu. Merci pour la mise à jour!

**Comment by jperon** [comment]
Merci à vous pour le signalement !
