### ISSUE TITLE
stack docker-compose

### ISSUE THREAD

**Issue by mqu** [jperon/pmb#3]
bonjour,

je me suis permis de réutiliser ce travail de fabrication de container docker afin de l'intégrer sous forme de stack docker-compose un peu plus complète. Merci pour votre contribution initiale.

Voici le lien vers cette version alternative : https://github.com/mqu/pmb-ils/

cordialement, Marc.

**Comment by jperon** [comment]
Excellent ! Je pense conserver ce dépôt en maintenance un peu large, pour ceux qui préféreraient une installation "quick-n-dirty", mais je vais ajouter un lien pointant vers votre dépôt.

**Comment by mqu** [comment]
merci ; tout est parfait comme cela. La simplicité ne nuit pas à la lisibilité ; avec un peu de complexité, je pense qu'on ne peut pas en dire autant.
